const PRODUCTS = [
  // ===== INDICA =====
  { name: "Capone Kush", price: 180, category: "indica", image: "images/products/capone-kush.jpeg", badge: "latest",
    tiers: [["1G",15],["3.5G",30],["5G",40],["7G",60],["10G",75],["14G",100],["OZ",180]] },
  { name: "Lights Out OG", price: 150, category: "indica", image: "images/products/lights-out-og.jpeg", badge: "latest",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "Dante's Inferno Smalls", price: 80, category: "indica", image: "images/products/dantes-inferno-smalls.jpeg", badge: "popular",
    tiers: [["1G",10],["3.5G",20],["5G",25],["7G",35],["10G",45],["14G",60],["OZ",80]] },
  { name: "Syndicate", price: 200, category: "indica", image: "images/products/syndicate.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",60],["10G",80],["14G",110],["OZ",200]] },
  { name: "West Coast OG", price: 260, category: "indica", image: "images/products/west-coast-og.jpeg",
    tiers: [["1G",20],["3.5G",50],["5G",65],["7G",85],["10G",120],["14G",150],["OZ",260]] },
  { name: "3 Kings OG", price: 180, category: "indica", image: "images/products/3-kings-og.jpg",
    tiers: [["1G",15],["3.5G",30],["5G",40],["7G",60],["10G",75],["14G",100],["OZ",180]] },
  { name: "Northern Lights", price: 100, category: "indica", image: "images/products/northern-lights.jpeg",
    tiers: [["1G",10],["3.5G",30],["5G",35],["10G",55],["14G",65],["OZ",100]] },
  { name: "XXX OG", price: 200, category: "indica", image: "images/products/xxx-og.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",60],["10G",85],["14G",110],["OZ",200]] },
  { name: "Bugatti OG", price: 150, category: "indica", image: "images/products/bugatti-og.jpeg",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "Skywalker", price: 180, category: "indica", image: "images/products/skywalker.jpeg",
    tiers: [["1G",15],["3.5G",30],["5G",40],["7G",60],["10G",75],["14G",100],["OZ",180]] },
  { name: "Atomic", price: 150, category: "indica", image: "images/products/atomic-indica.jpeg",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "Blue Shamu", price: 150, category: "indica", image: "images/products/blue-shamu.jpeg",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "Hell's Fire", price: 100, category: "indica", image: "images/products/hells-fire.jpeg",
    tiers: [["1G",10],["3.5G",30],["5G",35],["10G",55],["14G",65],["OZ",100]] },
  { name: "Black Maple", price: 150, category: "indica", image: "images/products/black-maple.jpeg",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "Emerald OG", price: 180, category: "indica", image: "images/products/emerald-og.jpeg",
    tiers: [["1G",15],["3.5G",30],["5G",40],["7G",60],["10G",75],["14G",100],["OZ",180]] },
  { name: "Black Runtz", price: 200, category: "indica", image: "images/products/black-runtz.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",60],["10G",80],["14G",110],["OZ",200]] },
  { name: "Gas Face OG", price: 180, category: "indica", image: "images/products/gas-face-og.jpeg",
    tiers: [["1G",15],["3.5G",30],["5G",40],["7G",60],["10G",75],["14G",100],["OZ",180]] },
  { name: "Dante's Inferno", price: 200, category: "indica", image: "images/products/dantes-inferno.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",60],["10G",80],["14G",110],["OZ",200]] },
  { name: "King Mamba", price: 250, category: "indica", image: "images/products/king-mamba.jpeg",
    tiers: [["1G",20],["3.5G",50],["5G",65],["7G",85],["10G",120],["14G",150],["OZ",250]] },
  { name: "Chaos OG", price: 240, category: "indica", image: "images/products/chaos-og.jpeg",
    tiers: [["1G",20],["3.5G",45],["5G",60],["7G",80],["10G",110],["14G",140],["OZ",240]] },
  { name: "Josh D OG", price: 220, category: "indica", image: "images/products/josh-d-og.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",65],["10G",85],["14G",120],["OZ",220]] },
  { name: "Rambo OG", price: 200, category: "indica", image: "images/products/rambo-og.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",60],["10G",80],["14G",110],["OZ",200]] },
  { name: "Gas Gimlet", price: 240, category: "indica", image: "images/products/gas-gimlet.jpeg",
    tiers: [["1G",20],["3.5G",45],["5G",60],["7G",80],["10G",110],["14G",140],["OZ",240]] },
  { name: "Blackberry Kush", price: 150, category: "indica", image: "images/products/blackberry-kush.jpeg",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "Grape Ape", price: 150, category: "indica", image: "images/products/grape-ape.jpeg",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "Faceoff", price: 180, category: "indica", image: "images/products/faceoff.jpeg",
    tiers: [["1G",15],["3.5G",30],["5G",40],["7G",60],["10G",75],["14G",100],["OZ",180]] },
  { name: "Gangster OG", price: 200, category: "indica", image: "images/products/gangster-og.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",60],["10G",80],["14G",110],["OZ",200]] },
  { name: "Purple Pomegranate", price: 100, category: "indica", image: "images/products/purple-pomegranate.jpeg",
    tiers: [["1G",10],["3.5G",30],["5G",35],["10G",55],["14G",65],["OZ",100]] },

  // ===== SATIVA =====
  { name: "Candyland", price: 80, category: "sativa", image: "images/products/candyland.jpeg", badge: "latest",
    tiers: [["1G",10],["3.5G",20],["5G",25],["7G",35],["10G",45],["14G",60],["OZ",80]] },
  { name: "Moose and Lobster", price: 100, category: "sativa", image: "images/products/moose-and-lobster.jpeg", badge: "latest",
    tiers: [["1G",10],["3.5G",30],["5G",35],["10G",55],["14G",65],["OZ",100]] },
  { name: "Super Lemon Haze", price: 200, category: "sativa", image: "images/products/super-lemon-haze.jpg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",60],["10G",80],["14G",110],["OZ",200]] },
  { name: "Mind Shift", price: 220, category: "sativa", image: "images/products/mind-shift.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",65],["10G",85],["14G",120],["OZ",220]] },
  { name: "Solar Rush", price: 180, category: "sativa", image: "images/products/solar-rush.jpeg",
    tiers: [["1G",15],["3.5G",30],["5G",40],["7G",60],["10G",75],["14G",100],["OZ",180]] },
  { name: "Super Sour Orange", price: 200, category: "sativa", image: "images/products/super-sour-orange.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",60],["10G",80],["14G",110],["OZ",200]] },
  { name: "Atomic Apple", price: 220, category: "sativa", image: "images/products/atomic-apple.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",65],["10G",85],["14G",120],["OZ",220]] },
  { name: "Sugar Sap", price: 150, category: "sativa", image: "images/products/sugar-sap.jpeg",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "Jack the Ripper", price: 180, category: "sativa", image: "images/products/jack-the-ripper.jpeg",
    tiers: [["1G",15],["3.5G",30],["5G",40],["7G",60],["10G",75],["14G",100],["OZ",180]] },
  { name: "Blue Zlushie", price: 240, category: "sativa", image: "images/products/blue-zlushie.jpeg",
    tiers: [["1G",20],["3.5G",45],["5G",60],["7G",80],["10G",110],["14G",140],["OZ",240]] },
  { name: "Hawaiian Snow", price: 150, category: "sativa", image: "images/products/hawaiian-snow.jpeg",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "Sour Tangie", price: 100, category: "sativa", image: "images/products/sour-tangie.jpg",
    tiers: [["1G",10],["3.5G",25],["5G",30],["7G",35],["10G",55],["14G",65],["OZ",100]] },
  { name: "Zuzu Berry", price: 100, category: "sativa", image: "images/products/zuzu-berry.jpg",
    tiers: [["1G",10],["3.5G",25],["5G",30],["7G",35],["10G",55],["14G",65],["OZ",100]] },
  { name: "GB Extracts Moonrocks (Strawberry)", price: 45, category: "sativa", image: "images/products/gb-moonrocks.jpg",
    tiers: [["3.5G",45]] },
  { name: "GB Extracts Moonrocks (Green Apple)", price: 45, category: "sativa", image: "images/products/gb-moonrocks.jpg",
    tiers: [["3.5G",45]] },

  // ===== HYBRID =====
  { name: "John Gotti OG", price: 180, category: "hybrid", image: "images/products/John-gotta-og.jpeg", badge: "latest",
    tiers: [["1G",15],["3.5G",30],["5G",40],["7G",60],["10G",75],["14G",100],["OZ",180]] },
  { name: "KnockOut OG", price: 150, category: "hybrid", image: "images/products/knockout-og.jpeg", badge: "latest",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "Bangers and Mac Smalls", price: 85, category: "hybrid", image: "images/products/bangers-and-mac-smalls.jpg", badge: "latest",
    tiers: [["1G",10],["3.5G",20],["5G",25],["7G",35],["14G",60],["OZ",85]] },
  { name: "Cereal Milk", price: 100, category: "hybrid", image: "images/products/cereal-milk.jpeg", badge: "popular",
    tiers: [["1G",10],["3.5G",30],["5G",35],["10G",55],["14G",65],["OZ",100]] },
  { name: "Zen Wen", price: 260, category: "hybrid", image: "images/products/zen-wen.jpeg", badge: "popular",
    tiers: [["1G",20],["3.5G",50],["5G",65],["7G",85],["10G",120],["14G",150],["OZ",260]] },
  { name: "Alien OG", price: 200, category: "hybrid", image: "images/products/alien-og.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",60],["10G",85],["14G",110],["OZ",200]] },
  { name: "Wedding Cake", price: 150, category: "hybrid", image: "images/products/wedding-cake.jpeg",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "Blue Viper", price: 150, category: "hybrid", image: "images/products/blue-viper.jpeg",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "Purple Pom", price: 100, category: "hybrid", image: "images/products/purple-pom.jpeg",
    tiers: [["1G",10],["3.5G",30],["5G",35],["10G",55],["14G",65],["OZ",100]] },
  { name: "Couch Rider", price: 220, category: "hybrid", image: "images/products/couch-rider.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",65],["10G",85],["14G",120],["OZ",220]] },
  { name: "Grape Diesel", price: 180, category: "hybrid", image: "images/products/grape-diesel.jpeg",
    tiers: [["1G",15],["3.5G",30],["5G",40],["7G",60],["10G",75],["14G",100],["OZ",180]] },
  { name: "Animal Face", price: 150, category: "hybrid", image: "images/products/animal-face.jpeg",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "RS11", price: 100, category: "hybrid", image: "images/products/rs11.jpeg",
    tiers: [["1G",10],["3.5G",30],["5G",35],["10G",55],["14G",65],["OZ",100]] },
  { name: "Jealousy", price: 150, category: "hybrid", image: "images/products/jealousy.jpeg",
    tiers: [["1G",12],["3.5G",30],["5G",35],["7G",50],["10G",65],["14G",80],["OZ",150]] },
  { name: "High Octane", price: 220, category: "hybrid", image: "images/products/high-octane.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",65],["10G",85],["14G",120],["OZ",220]] },
  { name: "Sweet N Sour", price: 180, category: "hybrid", image: "images/products/sweet-n-sour.jpeg",
    tiers: [["1G",15],["3.5G",30],["5G",40],["7G",60],["10G",75],["14G",100],["OZ",180]] },
  { name: "Planetary OG", price: 200, category: "hybrid", image: "images/products/planetary-og.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",60],["10G",80],["14G",110],["OZ",200]] },
  { name: "Project 4516", price: 200, category: "hybrid", image: "images/products/project-4516.jpeg",
    tiers: [["1G",15],["3.5G",35],["5G",45],["7G",60],["10G",80],["14G",110],["OZ",200]] },
  { name: "Citral Glue", price: 250, category: "hybrid", image: "images/products/citral-glue.jpeg",
    tiers: [["1G",20],["3.5G",50],["5G",65],["7G",85],["10G",120],["14G",150],["OZ",250]] },
  { name: "Sherb Cake", price: 100, category: "hybrid", image: "images/products/sherb-cake.jpg",
    tiers: [["1G",10],["3.5G",25],["5G",30],["7G",35],["10G",55],["14G",65],["OZ",100]] },
  { name: "GB Extracts Moonrocks Melon", price: 45, category: "hybrid", image: "images/products/gb-moonrocks-melon.jpg",
    tiers: [["3.5G",45]] },

  // ===== PRE-ROLLS & BLUNTS =====
  { name: "Devour Diamond Coated 2G Preroll - Blackberry Kush", price: 20, category: "pre-rolls", image: "images/products/devour-preroll.webp", tiers: [["EA",20]] },
  { name: "Devour Diamond Coated 2G Preroll - Jack Herer", price: 20, category: "pre-rolls", image: "images/products/devour-preroll.webp", tiers: [["EA",20]] },
  { name: "Devour Diamond Coated 2G Preroll - Wedding Pie", price: 20, category: "pre-rolls", image: "images/products/devour-preroll.webp", tiers: [["EA",20]] },
  { name: "Devour Diamond Coated 2G Preroll - Gelato", price: 20, category: "pre-rolls", image: "images/products/devour-preroll.webp", tiers: [["EA",20]] },
  { name: "Devour Diamond Coated 2G Preroll - Pineapple Express", price: 20, category: "pre-rolls", image: "images/products/devour-preroll.webp", tiers: [["EA",20]] },
  { name: "Mad Rippers 1.5G Prerolls - Lemon Cherry Gelato", price: 8, category: "pre-rolls", image: "images/products/mad-rippers.jpg", tiers: [["EA",8]] },
  { name: "Mad Rippers 1.5G Prerolls - Watermelon Gushers", price: 8, category: "pre-rolls", image: "images/products/mad-rippers.jpg", tiers: [["EA",8]] },
  { name: "Mad Rippers 1.5G Prerolls - Maui Wowie", price: 8, category: "pre-rolls", image: "images/products/mad-rippers.jpg", tiers: [["EA",8]] },
  { name: "Mad Rippers 1.5G Prerolls - Skywalker OG", price: 8, category: "pre-rolls", image: "images/products/mad-rippers.jpg", tiers: [["EA",8]] },
  { name: "GB Extracts Moon Rock - Strawberry 2.5G Blunt", price: 35, category: "pre-rolls", image: "images/products/gb-blunt.jpg", tiers: [["EA",35]] },
  { name: "GB Extracts Moon Rock - Melon 2.5G Blunt", price: 35, category: "pre-rolls", image: "images/products/gb-blunt.jpg", tiers: [["EA",35]] },

  // ===== EDIBLES =====
  { name: "TCF Canna Butter Unsalted 1000mg THC", price: 30, category: "edibles", image: "images/products/tcf-canna-butter.jpeg", tiers: [["EA",30]] },
  { name: "TCF Space Brownie 1000mg THC", price: 30, category: "edibles", image: "images/products/tcf-space-brownie.jpg", tiers: [["EA",30]] },
  { name: "Devour High Crawlers Sour Worms 1500mg THC", price: 25, category: "edibles", image: "images/products/devour-high-crawlers.jpg", tiers: [["EA",25]] },
  { name: "Devour Sour Apple Rings 1500mg THC", price: 25, category: "edibles", image: "images/products/devour-sour-apple.jpg", tiers: [["EA",25]] },
  { name: "Devour Watermelon Sour Rings 1500mg THC", price: 25, category: "edibles", image: "images/products/devour-watermelon-rings.jpg", tiers: [["EA",25]] },
  { name: "Devour Watermelon Slices 1500mg THC", price: 25, category: "edibles", image: "images/products/devour-watermelon-slices.jpg", tiers: [["EA",25]] },
  { name: "The Cookie Factory Blackout Brownie 1000mg THC", price: 30, category: "edibles", image: "images/products/tcf-blackout-brownie.jpg", tiers: [["EA",30]] },
  { name: "Devour Live Rosin Gummies 3000mg THC - Watermelon Lime", price: 40, category: "edibles", image: "images/products/devour-live-rosin.jpeg", badge: "latest", tiers: [["EA",40],["3 for",100]] },
  { name: "Devour Live Rosin Gummies 3000mg THC - Strawberry Blueberry", price: 40, category: "edibles", image: "images/products/devour-live-rosin.jpeg", badge: "latest", tiers: [["EA",40],["3 for",100]] },
  { name: "Devour Sour Lasso 1500mg THC - Watermelon", price: 25, category: "edibles", image: "images/products/devour-sour-lasso.jpeg", badge: "latest", tiers: [["EA",25]] },
  { name: "Devour Sour Lasso 1500mg THC - Strawberry", price: 25, category: "edibles", image: "images/products/devour-sour-lasso.jpeg", badge: "latest", tiers: [["EA",25]] },
  { name: "Devour Sour Mango 1500mg THC", price: 25, category: "edibles", image: "images/products/devour-sour-mango.jpeg", badge: "latest", tiers: [["EA",25]] },
  { name: "Devour Sour Rings 750mg THC - Watermelon", price: 20, category: "edibles", image: "images/products/devour-sour-rings.jpeg", badge: "latest", tiers: [["EA",20]] },
  { name: "Devour Sour Rings 750mg THC - Apple", price: 20, category: "edibles", image: "images/products/devour-sour-rings.jpeg", badge: "latest", tiers: [["EA",20]] },

  // ===== WAX =====
  { name: "GB Extract Syringe - Pineapple Express", price: 20, category: "wax", image: "images/products/gb-syringe.jpg", tiers: [["1G",20]] },
  { name: "GB Extract Syringe - True OG", price: 20, category: "wax", image: "images/products/gb-syringe.jpg", tiers: [["1G",20]] },
  { name: "GB Extract Syringe - Fire OG", price: 20, category: "wax", image: "images/products/gb-syringe.jpg", tiers: [["1G",20]] },
  { name: "GB Extract Syringe - Paris OG", price: 20, category: "wax", image: "images/products/gb-syringe.jpg", tiers: [["1G",20]] },
  { name: "GB Extract Syringe - Girl Scout Cookies", price: 20, category: "wax", image: "images/products/gb-syringe.jpg", tiers: [["1G",20]] },
  { name: "GB Extract Syringe - Sour Tangie", price: 20, category: "wax", image: "images/products/gb-syringe-2.jpeg", tiers: [["1G",20]] },
  { name: "GB Extract Syringe - Blue Dream", price: 20, category: "wax", image: "images/products/gb-syringe-2.jpeg", tiers: [["1G",20]] },
  { name: "GB Extract Syringe - Premium Jack", price: 20, category: "wax", image: "images/products/gb-syringe-2.jpeg", tiers: [["1G",20]] },
  { name: "GB Extract Syringe - Gorilla Glue", price: 20, category: "wax", image: "images/products/gb-syringe-2.jpeg", tiers: [["1G",20]] },
  { name: "GB Extract Syringe - Strawnana", price: 20, category: "wax", image: "images/products/gb-syringe-2.jpeg", tiers: [["1G",20]] },
  { name: "GB Extracts Shatter", price: 25, category: "wax", image: "images/products/gb-shatter.jpeg", tiers: [["1G",25],["5G",100]] },
  { name: "GB Extracts Sugar Sauce - Strawnana", price: 20, category: "wax", image: "images/products/gb-sugar-sauce.jpeg", tiers: [["1G",20]] },
  { name: "GB Extracts Sugar Sauce - Wifi", price: 20, category: "wax", image: "images/products/gb-sugar-sauce.jpeg", tiers: [["1G",20]] },
  { name: "GB Extracts Sugar Sauce - Fire OG", price: 20, category: "wax", image: "images/products/gb-sugar-sauce.jpeg", tiers: [["1G",20]] },
  { name: "Bomb Crumble - Oreoz", price: 25, category: "wax", image: "images/products/bomb-crumble.jpg", tiers: [["1G",25],["5G",100]] },
  { name: "Bomb Crumble - London Pound Cake", price: 25, category: "wax", image: "images/products/bomb-crumble.jpg", tiers: [["1G",25],["5G",100]] },
  { name: "Bomb Crumble - SFV OG", price: 25, category: "wax", image: "images/products/bomb-crumble.jpg", tiers: [["1G",25],["5G",100]] },
  { name: "West Coast Cure Live Resin Sauce - Sylmar", price: 30, category: "wax", image: "images/products/wcc-sauce.jpg", tiers: [["1G",30]] },
  { name: "West Coast Cure Live Resin Badder - Forbidden Haze", price: 30, category: "wax", image: "images/products/wcc-badder.jpg", tiers: [["1G",30]] },
  { name: "Devour GG4 Shatter", price: 25, category: "wax", image: "images/products/devour-shatter.jpg", tiers: [["1G",25],["5G",100]] },
  { name: "Devour Gushers Shatter", price: 25, category: "wax", image: "images/products/devour-shatter.jpg", tiers: [["1G",25],["5G",100]] },
  { name: "Stiiizy Syringe - Hardcore OG", price: 40, category: "wax", image: "images/products/stiiizy-syringe.jpg", tiers: [["1G",40]] },

  // ===== VAPES =====
  { name: "Taffy 2G Disposable - Ice Cream Cake", price: 45, category: "vapes", image: "images/products/taffy-disposable.jpeg", tiers: [["2G",45],["2 for",65]] },
  { name: "Taffy 2G Disposable - Sour Diesel", price: 45, category: "vapes", image: "images/products/taffy-disposable.jpeg", tiers: [["2G",45],["2 for",65]] },
  { name: "Taffy 2G Disposable - Pineapple Express", price: 45, category: "vapes", image: "images/products/taffy-disposable.jpeg", tiers: [["2G",45],["2 for",65]] },
  { name: "Taffy 2G Disposable - Lemon Haze", price: 45, category: "vapes", image: "images/products/taffy-disposable.jpeg", tiers: [["2G",45],["2 for",65]] },
  { name: "Taffy 2G Disposable - Pink Runtz", price: 45, category: "vapes", image: "images/products/taffy-disposable.jpeg", tiers: [["2G",45],["2 for",65]] },
  { name: "Taffy 2G Disposable - Strawberry Cough", price: 45, category: "vapes", image: "images/products/taffy-disposable.jpeg", tiers: [["2G",45],["2 for",65]] },
  { name: "Taffy 2G Disposable - Zkittlez", price: 45, category: "vapes", image: "images/products/taffy-disposable.jpeg", tiers: [["2G",45],["2 for",65]] },
  { name: "Taffy 2G Disposable - Gassy Taffy", price: 45, category: "vapes", image: "images/products/taffy-disposable.jpeg", tiers: [["2G",45],["2 for",65]] },
  { name: "Taffy 2G Disposable - King Louie", price: 45, category: "vapes", image: "images/products/taffy-disposable.jpeg", tiers: [["2G",45],["2 for",65]] },
  { name: "Taffy 2G Disposable - White Rhino", price: 45, category: "vapes", image: "images/products/taffy-disposable.jpeg", tiers: [["2G",45],["2 for",65]] },
  { name: "PlugPlay - Island Sweet Skunk", price: 45, category: "vapes", image: "images/products/plugplay-pod.jpeg", tiers: [["1G",45]] },
  { name: "PlugPlay - Super Lemon Haze", price: 45, category: "vapes", image: "images/products/plugplay-pod-2.jpg", tiers: [["1G",45]] },
  { name: "PlugPlay - Northern Light", price: 45, category: "vapes", image: "images/products/plugplay-pod.jpeg", tiers: [["1G",45]] },
  { name: "Blinkers Disposable 3.5G - Runtz", price: 60, category: "vapes", image: "images/products/blinkers-disposable.jpg", tiers: [["3.5G",60],["2 for",110],["3 for",150]] },
  { name: "Blinkers Disposable 3.5G - Incredible Hulk", price: 60, category: "vapes", image: "images/products/blinkers-disposable.jpg", tiers: [["3.5G",60],["2 for",110],["3 for",150]] },
  { name: "Blinkers Disposable 3.5G - OG", price: 60, category: "vapes", image: "images/products/blinkers-disposable.jpg", tiers: [["3.5G",60],["2 for",110],["3 for",150]] },
  { name: "Blinkers Disposable 3.5G - Banana Runtz", price: 60, category: "vapes", image: "images/products/blinkers-disposable.jpg", tiers: [["3.5G",60],["2 for",110],["3 for",150]] },
  { name: "Blinkers Disposable 3.5G - Superglue", price: 60, category: "vapes", image: "images/products/blinkers-disposable.jpg", tiers: [["3.5G",60],["2 for",110],["3 for",150]] },
  { name: "Blinkers Disposable 3.5G - Pink Champagne", price: 60, category: "vapes", image: "images/products/blinkers-disposable.jpg", tiers: [["3.5G",60],["2 for",110],["3 for",150]] },
  { name: "Blinkers Disposable 3.5G - Birthday Cake", price: 60, category: "vapes", image: "images/products/blinkers-disposable.jpg", tiers: [["3.5G",60],["2 for",110],["3 for",150]] },
  { name: "Blinkers Disposable 3.5G - Hindu Kush", price: 60, category: "vapes", image: "images/products/blinkers-disposable.jpg", tiers: [["3.5G",60],["2 for",110],["3 for",150]] },
  { name: "Blinkers Disposable 3.5G - Gushers", price: 60, category: "vapes", image: "images/products/blinkers-disposable.jpg", tiers: [["3.5G",60],["2 for",110],["3 for",150]] },
  { name: "Blinkers Disposable 3.5G - Zkittlez", price: 60, category: "vapes", image: "images/products/blinkers-disposable.jpg", tiers: [["3.5G",60],["2 for",110],["3 for",150]] },
  { name: "Blinkers Disposable 3.5G - Maui Wowie", price: 60, category: "vapes", image: "images/products/blinkers-disposable.jpg", tiers: [["3.5G",60],["2 for",110],["3 for",150]] },
  { name: "Litto Disposable 3G - Super Lemon Haze", price: 60, category: "vapes", image: "images/products/litto-disposable.jpg", tiers: [["3G",60]] },
  { name: "Jeeter Juice - Watermelon Zkittlez", price: 20, category: "vapes", image: "images/products/jeeter-juice.jpg", tiers: [["1G",20],["6 for",100]] },
  { name: "Jeeter Juice - Strawberry Shortcake", price: 20, category: "vapes", image: "images/products/jeeter-juice.jpg", tiers: [["1G",20],["6 for",100]] },
  { name: "Stiiizy Pod - Gelato", price: 20, category: "vapes", image: "images/products/stiiizy-pod.jpg", tiers: [["0.5G",20]] },
  { name: "Stiiizy Pod - Pineapple Express", price: 20, category: "vapes", image: "images/products/stiiizy-pod.jpg", tiers: [["0.5G",20]] },
  { name: "Stiiizy Pod - Do-Si-Dos", price: 20, category: "vapes", image: "images/products/stiiizy-pod.jpg", tiers: [["0.5G",20]] },
  { name: "Stiiizy Pod - Sour Diesel", price: 20, category: "vapes", image: "images/products/stiiizy-pod.jpg", tiers: [["0.5G",20]] },
  { name: "Stiiizy Pod - White Raspberry", price: 20, category: "vapes", image: "images/products/stiiizy-pod.jpg", tiers: [["0.5G",20]] },
  { name: "Stiiizy Pod - Biscotti", price: 20, category: "vapes", image: "images/products/stiiizy-pod.jpg", tiers: [["0.5G",20]] },
  { name: "Dime Live Reserve - Papaya", price: 40, category: "vapes", image: "images/products/dime-disposable.jpg", tiers: [["1G",40]] },
  { name: "Stiiizy - Blue Dream", price: 40, category: "vapes", image: "images/products/stiiizy-1g.jpg", tiers: [["1G",40]] },
  { name: "Stiiizy - Premium Jack", price: 40, category: "vapes", image: "images/products/stiiizy-1g.jpg", tiers: [["1G",40]] },
  { name: "Stiiizy - Orange Sunset Premium THC", price: 40, category: "vapes", image: "images/products/stiiizy-1g.jpg", tiers: [["1G",40]] },
  { name: "Stiiizy - Dub Breath Live Resin", price: 45, category: "vapes", image: "images/products/stiiizy-1g.jpg", tiers: [["1G",45]] },
  { name: "Stiiizy - Sour Cookies Live Resin", price: 30, category: "vapes", image: "images/products/stiiizy-1g.jpg", tiers: [["0.5G",30]] },
  { name: "Stiiizy - Sour Diesel Live Resin", price: 30, category: "vapes", image: "images/products/stiiizy-1g.jpg", tiers: [["0.5G",30]] },
  { name: "PlugPlay DNA - Durban Delight", price: 45, category: "vapes", image: "images/products/plugplay-dna.jpg", tiers: [["1G",45]] },
  { name: "PlugPlay DNA - Fire OG", price: 45, category: "vapes", image: "images/products/plugplay-dna.jpg", tiers: [["1G",45]] },
  { name: "PlugPlay DNA - Ghost Train", price: 45, category: "vapes", image: "images/products/plugplay-dna.jpg", tiers: [["1G",45]] },
  { name: "PlugPlay DNA - Sugar Daddy Purple", price: 45, category: "vapes", image: "images/products/plugplay-dna.jpg", tiers: [["1G",45]] },
  { name: "PlugPlay DNA - King Louie", price: 45, category: "vapes", image: "images/products/plugplay-dna.jpg", tiers: [["1G",45]] },
  { name: "PlugPlay DNA - Blue Dream", price: 45, category: "vapes", image: "images/products/plugplay-dna.jpg", tiers: [["1G",45]] },
  { name: "Sticky Stickz - Sticky OG", price: 40, category: "vapes", image: "images/products/sticky-stickz.jpg", tiers: [["1G",40]] },
  { name: "Interface Cartridge - Blueberry Pie", price: 20, category: "vapes", image: "images/products/interface-cart.jpg", tiers: [["1G",20],["6 for",100]] },
  { name: "Interface Cartridge - Watermelon Zkittlez", price: 20, category: "vapes", image: "images/products/interface-cart.jpg", tiers: [["1G",20],["6 for",100]] },
  { name: "Interface Cartridge - Jet Fuel", price: 20, category: "vapes", image: "images/products/interface-cart.jpg", tiers: [["1G",20],["6 for",100]] },
  { name: "Dr. Zodiak's Moonrock Clear - Bubble Gum", price: 40, category: "vapes", image: "images/products/dr-zodiaks.jpg", tiers: [["1G",40]] },
  { name: "Dr. Zodiak's Moonrock Clear - Frosty's Snowcone", price: 40, category: "vapes", image: "images/products/dr-zodiaks.jpg", tiers: [["1G",40]] },
  { name: "Dr. Zodiak's Moonrock Clear - Razzle Dazzle", price: 50, category: "vapes", image: "images/products/dr-zodiaks.jpg", tiers: [["1G",50]] },
  { name: "TCF Cartridge - Fire OG", price: 25, category: "vapes", image: "images/products/tcf-cart.jpg", tiers: [["1G",25]] },
  { name: "TCF Cartridge - True OG", price: 25, category: "vapes", image: "images/products/tcf-cart.jpg", tiers: [["1G",25]] },

  // ===== TINCTURE & TOPICALS =====
  { name: "Rubis Rub Eucalyptus CBD Bath Bomb", price: 10, category: "tincture-topicals", image: "images/products/rubis-eucalyptus.jpg", tiers: [["EA",10]] },
  { name: "Rubis Rub Jasmine CBD Bath Bomb", price: 10, category: "tincture-topicals", image: "images/products/rubis-jasmine.jpg", tiers: [["EA",10]] },
  { name: "Heavy Edibles 1000mg CBD Full Spectrum", price: 50, category: "tincture-topicals", image: "images/products/heavy-cbd.jpg", tiers: [["EA",50]] },
  { name: "4:1 CBD/THC Tincture", price: 40, category: "tincture-topicals", image: "images/products/cbd-tincture.png", tiers: [["EA",40]] },
  { name: "Lavender Pain Relieving Ultrabalm 500mg THC", price: 35, category: "tincture-topicals", image: "images/products/ultrabalm.png", tiers: [["EA",35],["2 for",60]] },

  // ===== GEAR =====
  { name: "18\" Tall Beaker Thick Glass", price: 150, category: "gear", image: "images/products/beaker-glass.jpeg", tiers: [["EA",150]], oldPrice: 200 },
  { name: "Stash Tray Trio Set", price: 15, category: "gear", image: "images/products/stash-tray.jpeg", tiers: [["EA",15]] },
  { name: "Stash Jar Airtight Lid", price: 10, category: "gear", image: "images/products/stash-jar.jpeg", tiers: [["EA",10]] },
  { name: "Hand Pipe 5\" Classic Glass Candy Cane Swirl", price: 10, category: "gear", image: "images/products/hand-pipe.jpg", tiers: [["EA",10]] },
  { name: "Blinkers 510 Thread Vape Battery", price: 15, category: "gear", image: "images/products/blinkers-battery.jpg", tiers: [["EA",15]] },
  { name: "PlugPlay Battery Red", price: 25, category: "gear", image: "images/products/plugplay-battery-red.jpg", tiers: [["EA",25]] },
  { name: "PlugPlay Battery Yellow", price: 25, category: "gear", image: "images/products/plugplay-battery-yellow.png", tiers: [["EA",25]] },
  { name: "PlugPlay Battery Black", price: 25, category: "gear", image: "images/products/plugplay-battery-black.png", tiers: [["EA",25]] },
  { name: "SQRL Red Battery Device", price: 25, category: "gear", image: "images/products/sqrl-red.jpg", tiers: [["EA",25]] },
  { name: "SQRL White Battery Device", price: 25, category: "gear", image: "images/products/sqrl-white.jpg", tiers: [["EA",25]] },
  { name: "SQRL Rose Gold Battery Device", price: 25, category: "gear", image: "images/products/sqrl-rosegold.jpg", tiers: [["EA",25]] },
  { name: "SQRL Prism Battery Device", price: 25, category: "gear", image: "images/products/sqrl-prism.jpg", tiers: [["EA",25]] },
  { name: "SQRL Black Device", price: 25, category: "gear", image: "images/products/sqrl-black.jpg", tiers: [["EA",25]] },
  { name: "SQRL Gold (Chrome) Device", price: 25, category: "gear", image: "images/products/sqrl-gold.jpg", tiers: [["EA",25]] },
  { name: "SQRL Blue Battery Device", price: 25, category: "gear", image: "images/products/sqrl-blue.jpg", tiers: [["EA",25]] }
];

const CATEGORIES = {
  "indica": { name: "Indica", slug: "indica" },
  "sativa": { name: "Sativa", slug: "sativa" },
  "hybrid": { name: "Hybrid", slug: "hybrid" },
  "pre-rolls": { name: "Pre-Rolls & Blunts", slug: "pre-rolls" },
  "edibles": { name: "Edibles", slug: "edibles" },
  "wax": { name: "Wax", slug: "wax" },
  "vapes": { name: "Vapes", slug: "vapes" },
  "tincture-topicals": { name: "Tincture & Topicals", slug: "tincture-topicals" },
  "gear": { name: "Gear", slug: "gear" }
};

function getProductTiers(product) {
  return product.tiers;
}

function getProductsByCategory(category) {
  return PRODUCTS.filter(function(p) { return p.category === category; });
}
