const PRODUCTS = [
  // ===== INDICA =====
  { name: "Dante's Inferno Smalls", price: 80, unit: "OZ", category: "indica", image: "images/products/dantes-inferno-smalls.jpeg", badge: "popular" },
  { name: "Syndicate", price: 200, unit: "OZ", category: "indica", image: "images/products/syndicate.jpeg" },
  { name: "West Coast OG", price: 260, unit: "OZ", category: "indica", image: "images/products/west-coast-og.jpeg" },
  { name: "3 Kings OG", price: 180, unit: "OZ", category: "indica", image: "images/products/3-kings-og.jpg" },
  { name: "Northern Lights", price: 100, unit: "OZ", category: "indica", image: "images/products/northern-lights.jpeg" },
  { name: "XXX OG", price: 200, unit: "OZ", category: "indica", image: "images/products/xxx-og.jpeg" },
  { name: "Bugatti OG", price: 150, unit: "OZ", category: "indica", image: "images/products/bugatti-og.jpeg" },
  { name: "Skywalker", price: 180, unit: "OZ", category: "indica", image: "images/products/skywalker.jpeg" },
  { name: "Atomic", price: 150, unit: "OZ", category: "indica", image: "images/products/atomic-indica.jpeg" },
  { name: "Dab Daddy", price: 75, unit: "OZ", category: "indica", image: "images/products/dab-daddy.jpeg" },
  { name: "Devils Cake", price: 75, unit: "OZ", category: "indica", image: "images/products/devils-cake.jpeg" },
  { name: "Blue Shamu", price: 150, unit: "OZ", category: "indica", image: "images/products/blue-shamu.jpeg" },
  { name: "Hell's Fire", price: 100, unit: "OZ", category: "indica", image: "images/products/hells-fire.jpeg" },
  { name: "Black Maple", price: 150, unit: "OZ", category: "indica", image: "images/products/black-maple.jpeg" },
  { name: "Emerald OG", price: 180, unit: "OZ", category: "indica", image: "images/products/emerald-og.jpeg" },
  { name: "Black Runtz", price: 200, unit: "OZ", category: "indica", image: "images/products/black-runtz.jpeg" },
  { name: "Banana Cream Cake", price: 75, unit: "OZ", category: "indica", image: "images/products/banana-cream-cake.jpeg" },
  { name: "Gas Face OG", price: 180, unit: "OZ", category: "indica", image: "images/products/gas-face-og.jpeg" },
  { name: "Dante's Inferno", price: 200, unit: "OZ", category: "indica", image: "images/products/dantes-inferno.jpeg" },
  { name: "King Mamba", price: 250, unit: "OZ", category: "indica", image: "images/products/king-mamba.jpeg" },
  { name: "Chaos OG", price: 240, unit: "OZ", category: "indica", image: "images/products/chaos-og.jpeg" },
  { name: "Josh D OG", price: 220, unit: "OZ", category: "indica", image: "images/products/josh-d-og.jpeg" },
  { name: "Rambo OG", price: 200, unit: "OZ", category: "indica", image: "images/products/rambo-og.jpeg" },
  { name: "Gas Gimlet", price: 240, unit: "OZ", category: "indica", image: "images/products/gas-gimlet.jpeg" },
  { name: "Blackberry Kush", price: 150, unit: "OZ", category: "indica", image: "images/products/blackberry-kush.jpeg" },
  { name: "Grape Ape", price: 150, unit: "OZ", category: "indica", image: "images/products/grape-ape.jpeg" },
  { name: "Faceoff", price: 180, unit: "OZ", category: "indica", image: "images/products/faceoff.jpeg" },
  { name: "Gangster OG", price: 200, unit: "OZ", category: "indica", image: "images/products/gangster-og.jpeg" },
  { name: "Purple Pomegranate", price: 100, unit: "OZ", category: "indica", image: "images/products/purple-pomegranate.jpeg" },

  // ===== SATIVA =====
  { name: "Candyland", price: 80, unit: "OZ", category: "sativa", image: "images/products/candyland.jpeg", badge: "latest" },
  { name: "Moose and Lobster", price: 100, unit: "OZ", category: "sativa", image: "images/products/moose-and-lobster.jpeg", badge: "latest" },
  { name: "Super Lemon Haze", price: 200, unit: "OZ", category: "sativa", image: "images/products/super-lemon-haze.jpg" },
  { name: "Mind Shift", price: 220, unit: "OZ", category: "sativa", image: "images/products/mind-shift.jpeg" },
  { name: "Solar Rush", price: 180, unit: "OZ", category: "sativa", image: "images/products/solar-rush.jpeg" },
  { name: "Super Sour Orange", price: 200, unit: "OZ", category: "sativa", image: "images/products/super-sour-orange.jpeg" },
  { name: "Atomic Apple", price: 220, unit: "OZ", category: "sativa", image: "images/products/atomic-apple.jpeg" },
  { name: "Blue Dream", price: 75, unit: "OZ", category: "sativa", image: "images/products/blue-dream.jpeg" },
  { name: "Sugar Sap", price: 150, unit: "OZ", category: "sativa", image: "images/products/sugar-sap.jpeg" },
  { name: "Jack the Ripper", price: 180, unit: "OZ", category: "sativa", image: "images/products/jack-the-ripper.jpeg" },
  { name: "Blue Zlushie", price: 240, unit: "OZ", category: "sativa", image: "images/products/blue-zlushie.jpeg" },
  { name: "Hawaiian Snow", price: 150, unit: "OZ", category: "sativa", image: "images/products/hawaiian-snow.jpeg" },
  { name: "Cherry Popperz", price: 75, unit: "OZ", category: "sativa", image: "images/products/cherry-popperz.jpeg" },
  { name: "Sour Tangie", price: 100, unit: "OZ", category: "sativa", image: "images/products/sour-tangie.jpg" },
  { name: "Zuzu Berry", price: 100, unit: "OZ", category: "sativa", image: "images/products/zuzu-berry.jpg" },
  { name: "GB Extracts Moonrocks (Strawberry)", price: 45, unit: "3.5G", category: "sativa", image: "images/products/gb-moonrocks.jpg" },
  { name: "GB Extracts Moonrocks (Green Apple)", price: 45, unit: "3.5G", category: "sativa", image: "images/products/gb-moonrocks.jpg" },

  // ===== HYBRID =====
  { name: "Bangers and Mac Smalls", price: 85, unit: "OZ", category: "hybrid", image: "images/products/bangers-and-mac-smalls.jpg", badge: "latest" },
  { name: "Cereal Milk", price: 100, unit: "OZ", category: "hybrid", image: "images/products/cereal-milk.jpeg", badge: "popular" },
  { name: "Zen Wen", price: 260, unit: "OZ", category: "hybrid", image: "images/products/zen-wen.jpeg", badge: "popular" },
  { name: "Alien OG", price: 200, unit: "OZ", category: "hybrid", image: "images/products/alien-og.jpeg" },
  { name: "Wedding Cake", price: 150, unit: "OZ", category: "hybrid", image: "images/products/wedding-cake.jpeg" },
  { name: "Pinky's Oreoz", price: 75, unit: "OZ", category: "hybrid", image: "images/products/pinkys-oreoz.jpeg" },
  { name: "Blue Viper", price: 150, unit: "OZ", category: "hybrid", image: "images/products/blue-viper.jpeg" },
  { name: "Purple Pom", price: 100, unit: "OZ", category: "hybrid", image: "images/products/purple-pom.jpeg" },
  { name: "Couch Rider", price: 220, unit: "OZ", category: "hybrid", image: "images/products/couch-rider.jpeg" },
  { name: "Grape Diesel", price: 180, unit: "OZ", category: "hybrid", image: "images/products/grape-diesel.jpeg" },
  { name: "Animal Face", price: 150, unit: "OZ", category: "hybrid", image: "images/products/animal-face.jpeg" },
  { name: "RS11", price: 100, unit: "OZ", category: "hybrid", image: "images/products/rs11.jpeg" },
  { name: "Jealousy", price: 150, unit: "OZ", category: "hybrid", image: "images/products/jealousy.jpeg" },
  { name: "Coma Cookies", price: 75, unit: "OZ", category: "hybrid", image: "images/products/coma-cookies.jpeg" },
  { name: "High Octane", price: 220, unit: "OZ", category: "hybrid", image: "images/products/high-octane.jpeg" },
  { name: "Sweet N Sour", price: 180, unit: "OZ", category: "hybrid", image: "images/products/sweet-n-sour.jpeg" },
  { name: "Planetary OG", price: 200, unit: "OZ", category: "hybrid", image: "images/products/planetary-og.jpeg" },
  { name: "Project 4516", price: 200, unit: "OZ", category: "hybrid", image: "images/products/project-4516.jpeg" },
  { name: "Citral Glue", price: 250, unit: "OZ", category: "hybrid", image: "images/products/citral-glue.jpeg" },
  { name: "Sherb Cake", price: 100, unit: "OZ", category: "hybrid", image: "images/products/sherb-cake.jpg" },
  { name: "GB Extracts Moonrocks Melon", price: 45, unit: "3.5G", category: "hybrid", image: "images/products/gb-moonrocks-melon.jpg" },

  // ===== PRE-ROLLS & BLUNTS =====
  { name: "Devour Diamond Coated 2G Preroll - Blackberry Kush", price: 20, unit: "EA", category: "pre-rolls", image: "images/products/devour-preroll.webp" },
  { name: "Devour Diamond Coated 2G Preroll - Jack Herer", price: 20, unit: "EA", category: "pre-rolls", image: "images/products/devour-preroll.webp" },
  { name: "Devour Diamond Coated 2G Preroll - Wedding Pie", price: 20, unit: "EA", category: "pre-rolls", image: "images/products/devour-preroll.webp" },
  { name: "Devour Diamond Coated 2G Preroll - Gelato", price: 20, unit: "EA", category: "pre-rolls", image: "images/products/devour-preroll.webp" },
  { name: "Devour Diamond Coated 2G Preroll - Pineapple Express", price: 20, unit: "EA", category: "pre-rolls", image: "images/products/devour-preroll.webp" },
  { name: "Mad Rippers 1.5G Prerolls - Lemon Cherry Gelato", price: 8, unit: "EA", category: "pre-rolls", image: "images/products/mad-rippers.jpg" },
  { name: "Mad Rippers 1.5G Prerolls - Watermelon Gushers", price: 8, unit: "EA", category: "pre-rolls", image: "images/products/mad-rippers.jpg" },
  { name: "Mad Rippers 1.5G Prerolls - Maui Wowie", price: 8, unit: "EA", category: "pre-rolls", image: "images/products/mad-rippers.jpg" },
  { name: "Mad Rippers 1.5G Prerolls - Skywalker OG", price: 8, unit: "EA", category: "pre-rolls", image: "images/products/mad-rippers.jpg" },
  { name: "GB Extracts Moon Rock - Strawberry 2.5G Blunt", price: 35, unit: "EA", category: "pre-rolls", image: "images/products/gb-blunt.jpg" },
  { name: "GB Extracts Moon Rock - Melon 2.5G Blunt", price: 35, unit: "EA", category: "pre-rolls", image: "images/products/gb-blunt.jpg" },

  // ===== EDIBLES =====
  { name: "TCF Canna Butter Unsalted 1000mg THC", price: 30, unit: "EA", category: "edibles", image: "images/products/tcf-canna-butter.jpeg" },
  { name: "Devour Pink Lemonade Sour Rings 1500mg THC", price: 25, unit: "EA", category: "edibles", image: "images/products/devour-pink-lemonade.jpeg" },
  { name: "TCF Space Brownie 1000mg THC", price: 30, unit: "EA", category: "edibles", image: "images/products/tcf-space-brownie.jpg" },
  { name: "Devour Sweet Villains 1500mg THC", price: 25, unit: "EA", category: "edibles", image: "images/products/devour-sweet-villains.jpg" },
  { name: "Devour High Crawlers Sour Worms 1500mg THC", price: 25, unit: "EA", category: "edibles", image: "images/products/devour-high-crawlers.jpg" },
  { name: "Devour Sour Apple Rings 1500mg THC", price: 25, unit: "EA", category: "edibles", image: "images/products/devour-sour-apple.jpg" },
  { name: "Devour Watermelon Sour Rings 1500mg THC", price: 25, unit: "EA", category: "edibles", image: "images/products/devour-watermelon-rings.jpg" },
  { name: "Devour Watermelon Slices 1500mg THC", price: 25, unit: "EA", category: "edibles", image: "images/products/devour-watermelon-slices.jpg" },
  { name: "The Cookie Factory Blackout Brownie 1000mg THC", price: 30, unit: "EA", category: "edibles", image: "images/products/tcf-blackout-brownie.jpg" },

  // ===== WAX =====
  { name: "GB Extract Syringe - Pineapple Express", price: 20, unit: "1G", category: "wax", image: "images/products/gb-syringe.jpg" },
  { name: "GB Extract Syringe - True OG", price: 20, unit: "1G", category: "wax", image: "images/products/gb-syringe.jpg" },
  { name: "GB Extract Syringe - Fire OG", price: 20, unit: "1G", category: "wax", image: "images/products/gb-syringe.jpg" },
  { name: "GB Extract Syringe - Paris OG", price: 20, unit: "1G", category: "wax", image: "images/products/gb-syringe.jpg" },
  { name: "GB Extract Syringe - Girl Scout Cookies", price: 20, unit: "1G", category: "wax", image: "images/products/gb-syringe.jpg" },
  { name: "GB Extract Syringe - Sour Tangie", price: 20, unit: "1G", category: "wax", image: "images/products/gb-syringe-2.jpeg" },
  { name: "GB Extract Syringe - Blue Dream", price: 20, unit: "1G", category: "wax", image: "images/products/gb-syringe-2.jpeg" },
  { name: "GB Extract Syringe - Premium Jack", price: 20, unit: "1G", category: "wax", image: "images/products/gb-syringe-2.jpeg" },
  { name: "GB Extract Syringe - Gorilla Glue", price: 20, unit: "1G", category: "wax", image: "images/products/gb-syringe-2.jpeg" },
  { name: "GB Extract Syringe - Strawnana", price: 20, unit: "1G", category: "wax", image: "images/products/gb-syringe-2.jpeg" },
  { name: "GB Extracts Shatter", price: 25, unit: "1G", category: "wax", image: "images/products/gb-shatter.jpeg", priceNote: "$100/5G" },
  { name: "GB Extracts Sugar Sauce - Strawnana", price: 20, unit: "1G", category: "wax", image: "images/products/gb-sugar-sauce.jpeg" },
  { name: "GB Extracts Sugar Sauce - Wifi", price: 20, unit: "1G", category: "wax", image: "images/products/gb-sugar-sauce.jpeg" },
  { name: "GB Extracts Sugar Sauce - Fire OG", price: 20, unit: "1G", category: "wax", image: "images/products/gb-sugar-sauce.jpeg" },
  { name: "Bomb Crumble - Oreoz", price: 25, unit: "1G", category: "wax", image: "images/products/bomb-crumble.jpg", priceNote: "$100/5G" },
  { name: "Bomb Crumble - London Pound Cake", price: 25, unit: "1G", category: "wax", image: "images/products/bomb-crumble.jpg", priceNote: "$100/5G" },
  { name: "Bomb Crumble - SFV OG", price: 25, unit: "1G", category: "wax", image: "images/products/bomb-crumble.jpg", priceNote: "$100/5G" },
  { name: "West Coast Cure Live Resin Sauce - Sylmar", price: 30, unit: "1G", category: "wax", image: "images/products/wcc-sauce.jpg" },
  { name: "West Coast Cure Live Resin Badder - Forbidden Haze", price: 30, unit: "1G", category: "wax", image: "images/products/wcc-badder.jpg" },
  { name: "Devour GG4 Shatter", price: 25, unit: "1G", category: "wax", image: "images/products/devour-shatter.jpg", priceNote: "$100/5G" },
  { name: "Devour Gushers Shatter", price: 25, unit: "1G", category: "wax", image: "images/products/devour-shatter.jpg", priceNote: "$100/5G" },
  { name: "Stiiizy Syringe - Hardcore OG", price: 40, unit: "1G", category: "wax", image: "images/products/stiiizy-syringe.jpg" },

  // ===== VAPES =====
  { name: "Taffy 2G Disposable - Ice Cream Cake", price: 45, unit: "2G", category: "vapes", image: "images/products/taffy-disposable.jpeg", priceNote: "2 for $65" },
  { name: "Taffy 2G Disposable - Sour Diesel", price: 45, unit: "2G", category: "vapes", image: "images/products/taffy-disposable.jpeg", priceNote: "2 for $65" },
  { name: "Taffy 2G Disposable - Pineapple Express", price: 45, unit: "2G", category: "vapes", image: "images/products/taffy-disposable.jpeg", priceNote: "2 for $65" },
  { name: "Taffy 2G Disposable - Lemon Haze", price: 45, unit: "2G", category: "vapes", image: "images/products/taffy-disposable.jpeg", priceNote: "2 for $65" },
  { name: "Taffy 2G Disposable - Pink Runtz", price: 45, unit: "2G", category: "vapes", image: "images/products/taffy-disposable.jpeg", priceNote: "2 for $65" },
  { name: "Taffy 2G Disposable - Strawberry Cough", price: 45, unit: "2G", category: "vapes", image: "images/products/taffy-disposable.jpeg", priceNote: "2 for $65" },
  { name: "Taffy 2G Disposable - Zkittlez", price: 45, unit: "2G", category: "vapes", image: "images/products/taffy-disposable.jpeg", priceNote: "2 for $65" },
  { name: "Taffy 2G Disposable - Gassy Taffy", price: 45, unit: "2G", category: "vapes", image: "images/products/taffy-disposable.jpeg", priceNote: "2 for $65" },
  { name: "Taffy 2G Disposable - King Louie", price: 45, unit: "2G", category: "vapes", image: "images/products/taffy-disposable.jpeg", priceNote: "2 for $65" },
  { name: "Taffy 2G Disposable - White Rhino", price: 45, unit: "2G", category: "vapes", image: "images/products/taffy-disposable.jpeg", priceNote: "2 for $65" },
  { name: "PlugPlay - Island Sweet Skunk", price: 45, unit: "1G", category: "vapes", image: "images/products/plugplay-pod.jpeg" },
  { name: "PlugPlay - Super Lemon Haze", price: 45, unit: "1G", category: "vapes", image: "images/products/plugplay-pod-2.jpg" },
  { name: "PlugPlay - Northern Light", price: 45, unit: "1G", category: "vapes", image: "images/products/plugplay-pod.jpeg" },
  { name: "Blinkers Disposable 3.5G - Runtz", price: 60, unit: "3.5G", category: "vapes", image: "images/products/blinkers-disposable.jpg", priceNote: "2/$110, 3/$150" },
  { name: "Blinkers Disposable 3.5G - Incredible Hulk", price: 60, unit: "3.5G", category: "vapes", image: "images/products/blinkers-disposable.jpg", priceNote: "2/$110, 3/$150" },
  { name: "Blinkers Disposable 3.5G - OG", price: 60, unit: "3.5G", category: "vapes", image: "images/products/blinkers-disposable.jpg", priceNote: "2/$110, 3/$150" },
  { name: "Blinkers Disposable 3.5G - Banana Runtz", price: 60, unit: "3.5G", category: "vapes", image: "images/products/blinkers-disposable.jpg", priceNote: "2/$110, 3/$150" },
  { name: "Blinkers Disposable 3.5G - Superglue", price: 60, unit: "3.5G", category: "vapes", image: "images/products/blinkers-disposable.jpg", priceNote: "2/$110, 3/$150" },
  { name: "Blinkers Disposable 3.5G - Pink Champagne", price: 60, unit: "3.5G", category: "vapes", image: "images/products/blinkers-disposable.jpg", priceNote: "2/$110, 3/$150" },
  { name: "Blinkers Disposable 3.5G - Birthday Cake", price: 60, unit: "3.5G", category: "vapes", image: "images/products/blinkers-disposable.jpg", priceNote: "2/$110, 3/$150" },
  { name: "Blinkers Disposable 3.5G - Hindu Kush", price: 60, unit: "3.5G", category: "vapes", image: "images/products/blinkers-disposable.jpg", priceNote: "2/$110, 3/$150" },
  { name: "Blinkers Disposable 3.5G - Gushers", price: 60, unit: "3.5G", category: "vapes", image: "images/products/blinkers-disposable.jpg", priceNote: "2/$110, 3/$150" },
  { name: "Blinkers Disposable 3.5G - Zkittlez", price: 60, unit: "3.5G", category: "vapes", image: "images/products/blinkers-disposable.jpg", priceNote: "2/$110, 3/$150" },
  { name: "Blinkers Disposable 3.5G - Maui Wowie", price: 60, unit: "3.5G", category: "vapes", image: "images/products/blinkers-disposable.jpg", priceNote: "2/$110, 3/$150" },
  { name: "Litto Disposable 3G - Super Lemon Haze", price: 60, unit: "3G", category: "vapes", image: "images/products/litto-disposable.jpg" },
  { name: "Jeeter Juice - Watermelon Zkittlez", price: 20, unit: "1G", category: "vapes", image: "images/products/jeeter-juice.jpg", priceNote: "6 for $100" },
  { name: "Jeeter Juice - Strawberry Shortcake", price: 20, unit: "1G", category: "vapes", image: "images/products/jeeter-juice.jpg", priceNote: "6 for $100" },
  { name: "Stiiizy Pod - Gelato", price: 20, unit: "0.5G", category: "vapes", image: "images/products/stiiizy-pod.jpg" },
  { name: "Stiiizy Pod - Pineapple Express", price: 20, unit: "0.5G", category: "vapes", image: "images/products/stiiizy-pod.jpg" },
  { name: "Stiiizy Pod - Do-Si-Dos", price: 20, unit: "0.5G", category: "vapes", image: "images/products/stiiizy-pod.jpg" },
  { name: "Stiiizy Pod - Sour Diesel", price: 20, unit: "0.5G", category: "vapes", image: "images/products/stiiizy-pod.jpg" },
  { name: "Stiiizy Pod - White Raspberry", price: 20, unit: "0.5G", category: "vapes", image: "images/products/stiiizy-pod.jpg" },
  { name: "Stiiizy Pod - Biscotti", price: 20, unit: "0.5G", category: "vapes", image: "images/products/stiiizy-pod.jpg" },
  { name: "Dime Live Reserve - Papaya", price: 40, unit: "1G", category: "vapes", image: "images/products/dime-disposable.jpg" },
  { name: "Stiiizy - Blue Dream", price: 40, unit: "1G", category: "vapes", image: "images/products/stiiizy-1g.jpg" },
  { name: "Stiiizy - Premium Jack", price: 40, unit: "1G", category: "vapes", image: "images/products/stiiizy-1g.jpg" },
  { name: "Stiiizy - Orange Sunset Premium THC", price: 40, unit: "1G", category: "vapes", image: "images/products/stiiizy-1g.jpg" },
  { name: "Stiiizy - Dub Breath Live Resin", price: 45, unit: "1G", category: "vapes", image: "images/products/stiiizy-1g.jpg" },
  { name: "Stiiizy - Sour Cookies Live Resin", price: 30, unit: "0.5G", category: "vapes", image: "images/products/stiiizy-1g.jpg" },
  { name: "Stiiizy - Sour Diesel Live Resin", price: 30, unit: "0.5G", category: "vapes", image: "images/products/stiiizy-1g.jpg" },
  { name: "PlugPlay DNA - Durban Delight", price: 45, unit: "1G", category: "vapes", image: "images/products/plugplay-dna.jpg" },
  { name: "PlugPlay DNA - Fire OG", price: 45, unit: "1G", category: "vapes", image: "images/products/plugplay-dna.jpg" },
  { name: "PlugPlay DNA - Ghost Train", price: 45, unit: "1G", category: "vapes", image: "images/products/plugplay-dna.jpg" },
  { name: "PlugPlay DNA - Sugar Daddy Purple", price: 45, unit: "1G", category: "vapes", image: "images/products/plugplay-dna.jpg" },
  { name: "PlugPlay DNA - King Louie", price: 45, unit: "1G", category: "vapes", image: "images/products/plugplay-dna.jpg" },
  { name: "PlugPlay DNA - Blue Dream", price: 45, unit: "1G", category: "vapes", image: "images/products/plugplay-dna.jpg" },
  { name: "Sticky Stickz - Sticky OG", price: 40, unit: "1G", category: "vapes", image: "images/products/sticky-stickz.jpg" },
  { name: "Interface Cartridge - Blueberry Pie", price: 20, unit: "1G", category: "vapes", image: "images/products/interface-cart.jpg", priceNote: "6 for $100" },
  { name: "Interface Cartridge - Watermelon Zkittlez", price: 20, unit: "1G", category: "vapes", image: "images/products/interface-cart.jpg", priceNote: "6 for $100" },
  { name: "Interface Cartridge - Jet Fuel", price: 20, unit: "1G", category: "vapes", image: "images/products/interface-cart.jpg", priceNote: "6 for $100" },
  { name: "Dr. Zodiak's Moonrock Clear - Bubble Gum", price: 40, unit: "1G", category: "vapes", image: "images/products/dr-zodiaks.jpg" },
  { name: "Dr. Zodiak's Moonrock Clear - Frosty's Snowcone", price: 40, unit: "1G", category: "vapes", image: "images/products/dr-zodiaks.jpg" },
  { name: "Dr. Zodiak's Moonrock Clear - Razzle Dazzle", price: 50, unit: "1G", category: "vapes", image: "images/products/dr-zodiaks.jpg" },
  { name: "TCF Cartridge - Fire OG", price: 25, unit: "1G", category: "vapes", image: "images/products/tcf-cart.jpg" },
  { name: "TCF Cartridge - True OG", price: 25, unit: "1G", category: "vapes", image: "images/products/tcf-cart.jpg" },

  // ===== TINCTURE & TOPICALS =====
  { name: "Rubis Rub Eucalyptus CBD Bath Bomb", price: 10, unit: "EA", category: "tincture-topicals", image: "images/products/rubis-eucalyptus.jpg" },
  { name: "Rubis Rub Jasmine CBD Bath Bomb", price: 10, unit: "EA", category: "tincture-topicals", image: "images/products/rubis-jasmine.jpg" },
  { name: "Heavy Edibles 1000mg CBD Full Spectrum", price: 50, unit: "EA", category: "tincture-topicals", image: "images/products/heavy-cbd.jpg" },
  { name: "4:1 CBD/THC Tincture", price: 40, unit: "EA", category: "tincture-topicals", image: "images/products/cbd-tincture.png" },
  { name: "Lavender Pain Relieving Ultrabalm 500mg THC", price: 35, unit: "EA", category: "tincture-topicals", image: "images/products/ultrabalm.png", priceNote: "2 for $60" },

  // ===== GEAR =====
  { name: "18\" Tall Beaker Thick Glass", price: 150, unit: "EA", category: "gear", image: "images/products/beaker-glass.jpeg", priceNote: "Was $200" },
  { name: "Stash Tray Trio Set", price: 15, unit: "EA", category: "gear", image: "images/products/stash-tray.jpeg" },
  { name: "Stash Jar Airtight Lid", price: 10, unit: "EA", category: "gear", image: "images/products/stash-jar.jpeg" },
  { name: "Hand Pipe 5\" Classic Glass Candy Cane Swirl", price: 10, unit: "EA", category: "gear", image: "images/products/hand-pipe.jpg" },
  { name: "Blinkers 510 Thread Vape Battery", price: 15, unit: "EA", category: "gear", image: "images/products/blinkers-battery.jpg" },
  { name: "PlugPlay Battery Red", price: 25, unit: "EA", category: "gear", image: "images/products/plugplay-battery-red.jpg" },
  { name: "PlugPlay Battery Yellow", price: 25, unit: "EA", category: "gear", image: "images/products/plugplay-battery-yellow.png" },
  { name: "PlugPlay Battery Black", price: 25, unit: "EA", category: "gear", image: "images/products/plugplay-battery-black.png" },
  { name: "SQRL Red Battery Device", price: 25, unit: "EA", category: "gear", image: "images/products/sqrl-red.jpg" },
  { name: "SQRL White Battery Device", price: 25, unit: "EA", category: "gear", image: "images/products/sqrl-white.jpg" },
  { name: "SQRL Rose Gold Battery Device", price: 25, unit: "EA", category: "gear", image: "images/products/sqrl-rosegold.jpg" },
  { name: "SQRL Prism Battery Device", price: 25, unit: "EA", category: "gear", image: "images/products/sqrl-prism.jpg" },
  { name: "SQRL Black Device", price: 25, unit: "EA", category: "gear", image: "images/products/sqrl-black.jpg" },
  { name: "SQRL Gold (Chrome) Device", price: 25, unit: "EA", category: "gear", image: "images/products/sqrl-gold.jpg" },
  { name: "SQRL Blue Battery Device", price: 25, unit: "EA", category: "gear", image: "images/products/sqrl-blue.jpg" }
];

const CATEGORIES = {
  "indica": { name: "Indica", slug: "indica" },
  "sativa": { name: "Sativa", slug: "sativa" },
  "hybrid": { name: "Hybrid", slug: "hybrid" },
  "pre-rolls": { name: "Pre-Rolls & Blunts", slug: "pre-rolls" },
  "edibles": { name: "Edibles", slug: "edibles" },
  "wax": { name: "Wax", slug: "wax" },
  "vapes": { name: "Vapes", slug: "vapes" },
  "tincture-topicals": { name: "Tincture & Topicals", slug: "tincture-topicals" },
  "gear": { name: "Gear", slug: "gear" }
};

function getProductsByCategory(category) {
  return PRODUCTS.filter(p => p.category === category);
}

function getLatestProducts(count = 6) {
  return PRODUCTS.filter(p => p.badge === "latest").concat(
    PRODUCTS.filter(p => !p.badge)
  ).slice(0, count);
}

function getPopularProducts(count = 6) {
  return PRODUCTS.filter(p => p.badge === "popular").concat(
    PRODUCTS.filter(p => !p.badge).sort(() => 0.5 - Math.random())
  ).slice(0, count);
}
